#!/usr/local/bin/bash
######################
# eZ - for scrub sites
# FreeBSD Locals Only

# USAGE ##############
if (( $# != 2 ))
then
	printf"\nUsage: \n";
	printf "ARG1 - URL to Scrape\n";
	printf "ARG2 - Dir to Dump\n";
	exit 1;
fi

url=$1
dump=$2
log="$dump/log"

num=0
while [ $num -lt 100000 ]
do
  printf "%s\n" "$num" >> $log;
  fetch -o $dump http://$url/$num.mp4;
  ((num++));
done
